// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpEQhIUG5rXMxfL-xbNufYKdYlg5MgEMo',
    appId: '1:268167252332:web:4cf7e8ab74cbef11784b49',
    messagingSenderId: '268167252332',
    projectId: 'ieltsspeaking-c1e51',
    authDomain: 'ieltsspeaking-c1e51.firebaseapp.com',
    storageBucket: 'ieltsspeaking-c1e51.appspot.com',
    measurementId: 'G-E0572Z5C31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZloIeKlf7N9rtY1ifVNRFThlkZvVq5pY',
    appId: '1:268167252332:android:49076466078d71e5784b49',
    messagingSenderId: '268167252332',
    projectId: 'ieltsspeaking-c1e51',
    storageBucket: 'ieltsspeaking-c1e51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxA6rGJVmdNpkC0vRI9EjZiau6feexnJs',
    appId: '1:268167252332:ios:b6d3a77fb7b9d9e0784b49',
    messagingSenderId: '268167252332',
    projectId: 'ieltsspeaking-c1e51',
    storageBucket: 'ieltsspeaking-c1e51.appspot.com',
    iosClientId: '268167252332-2u3ke14h5bg6g515307q4mukcerd0jv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieltsSpeaking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxA6rGJVmdNpkC0vRI9EjZiau6feexnJs',
    appId: '1:268167252332:ios:3819c25318bb2525784b49',
    messagingSenderId: '268167252332',
    projectId: 'ieltsspeaking-c1e51',
    storageBucket: 'ieltsspeaking-c1e51.appspot.com',
    iosClientId: '268167252332-l5bhn1fiaorl88acv17efv4vovbfu134.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieltsSpeaking.RunnerTests',
  );
}
